In [1]:
pip  install beautifulsoup4


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(
        """ 
            <html>
                <head>
                    <title> Hello</title>
                </head>
                <body>
                    <h1> Hello world</h1>
                    <p class="first"> this is the file</p>
                    <p id = "secondP"> this is second file</p>
                </body>
            </html>
        """,
        "html.parser"
)

In [3]:
print(soup.find("p"))
print(soup.find_all("p"))
print(soup.find(class_="first"))
print(soup.find(id="secondP"))
print(soup.find_all(class_="first"))
print(soup.find_all(id = "secondP"))
print(soup.select_one(".first"))
print(soup.select(".first"))

<p class="first"> this is the file</p>
[<p class="first"> this is the file</p>, <p id="secondP"> this is second file</p>]
<p class="first"> this is the file</p>
<p id="secondP"> this is second file</p>
[<p class="first"> this is the file</p>]
[<p id="secondP"> this is second file</p>]
<p class="first"> this is the file</p>
[<p class="first"> this is the file</p>]


In [4]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r"""
                <div class="product-listing"><div id="product-list-wrap" class="css-llpqn7"><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/dr-althea-resveratrol-345na-intensive-repair-cream/p/844890?productId=844890&amp;pps=1"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/6/5/657b0558809447251394_0.jpg" alt="Dr.Althea 345 Relief Cream: Soothing &amp; Barrier Repair Cream with power of Niacinamide &amp; Panthenol" class="css-11gn9r6"></div><img src="https://images-static.nykaa.com/media/OnlyatNykaaFinal.png" class="css-1xehky4"><div class="css-1rd7vky"><div class="css-xrzmfa">Dr.Althea 345 Relief Cream: Soothing &amp; Barrier Repair Cream ...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹2499</span></span><span class="css-111z9ua">₹2374</span><span class="css-cjd9an">5% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->361<!-- --> <!-- -->)</span></div><div class="css-i9shm8"></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class=" css-1oxhof2"><span class="btn-text">Add to Bag</span></button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/bioderma-atoderm-creme-ultra-nourishing-face-body-daily-care-normal-to-dry-skin/p/7483932?productId=7483932&amp;pps=2"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/f/4/f403ca9N_3401399459085_1.jpg" alt="Bioderma Niacinamide Moisturizer - Atoderm Creme Ultra-Boosts Hyaluronic Acid, Ceramides" class="css-11gn9r6"></div><div class="css-1rd7vky"><div class="css-xrzmfa">Bioderma Niacinamide Moisturizer - Atoderm Creme Ultra-Boost...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹699</span></span><span class="css-111z9ua">₹629</span><span class="css-cjd9an">10% Off</span></div><p color="0" class="css-1kzcg63">Get Complimentary Product</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->18148<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/lakme-peach-milk-soft-creme-moisturizer-377721/p/377721?productId=377721&amp;pps=3"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/d/0/d06aedfLAKME00001169_1.jpg" alt="Lakmé Peach Creme Moisturiser, Ceramide &amp; Peptide, Skin Barrier Repair &amp; Hydrated Glow" class="css-11gn9r6"></div><div class="css-1rd7vky"><div class="css-xrzmfa">Lakmé Peach Creme Moisturiser, Ceramide &amp; Peptide, Skin Barr...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹780</span></span><span class="css-111z9ua">₹390</span><span class="css-cjd9an">50% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->39534<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">4 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/forest-essentials-hydrating-facial-moisturiser-spf-25-sandalwood-orange-peel/p/16060292?productId=16060292&amp;skuId=1228792&amp;pps=4"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/1/2/1237e8fFORES00000048_1.jpg" alt="Forest Essentials Hydrating Facial Moisturiser with SPF 30 PA++ Sandalwood &amp; Orange Peel" class="css-11gn9r6"></div><div class="css-1rd7vky"><div class="css-xrzmfa">Forest Essentials Hydrating Facial Moisturiser with SPF 30 P...</div><div class="css-1d0jf8e"><span class="css-111z9ua">₹1695</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->979<!-- --> <!-- -->)</span></div><div class="css-i9shm8"></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class=" css-1oxhof2"><span class="btn-text">Add to Bag</span></button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/dot-key-vitamin-c-e-super-bright-moisturizer/p/2793282?productId=2793282&amp;pps=5"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/1/b/1b14b3eDOTKE00000054_e1.jpg" alt="Dot &amp; Key Vitamin C + E Super Bright Face Moisturizer For Glowing Skin, Fades Dark Spots" class="css-11gn9r6"></div><div class="css-1rd7vky"><div class="css-xrzmfa">Dot &amp; Key Vitamin C + E Super Bright Face Moisturizer For Gl...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹495</span></span><span class="css-111z9ua">₹426</span><span class="css-cjd9an">14% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Free Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->52190<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">3 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li><li aria-hidden="true" class="custom-tag css-astah5">NEW</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/la-roche-posay-cicaplast-baume-b5-repair-moisturizer-balm-soothing-cream/p/23326362?productId=23326362&amp;pps=6"><div class="css-43m2vm"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/4/9/49fafe2LAROC00000004_1.jpg" alt="La Roche-Posay Cicaplast Baume B5+ Repair Moisturizer Balm, Soothing cream for Dry, Sensitive Skin" class="css-11gn9r6"></div><img src="https://images-static.nykaa.com/media/OnlyatNykaaFinal.png" class="css-1xehky4"><div class="css-1rd7vky"><div class="css-xrzmfa">La Roche-Posay Cicaplast Baume B5+ Repair Moisturizer Balm, ...</div><div class="css-1d0jf8e"><span class="css-111z9ua">₹550</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->60<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/foxtale-nourishing-moisturiser-with-niacinamide-vit-e-for-24hr-hydration/p/18418255?productId=18418255&amp;pps=7"><div class="css-43m2vm"><div class="lazy-load-wrap"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/2/9/299a2c9FOXTA00000151_x1.jpg" alt="Foxtale Nourishing Ceramide Moisturiser for 100hrs of Hydrated, Glowing Skin" class="css-11gn9r6"></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Foxtale Nourishing Ceramide Moisturiser for 100hrs of Hydrat...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹395</span></span><span class="css-111z9ua">₹304</span><span class="css-cjd9an">23% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->5392<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/mamaearth-rice-oil-free-face-moisturizer-with-rice-water-niacinamide-for-glass-skin/p/5620403?productId=5620403&amp;pps=8"><div class="css-43m2vm"><div class="lazy-load-wrap"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/a/1/a1408d4MAMAE00000415_1.jpg" alt="Mamaearth Rice Oil-Free Face Moisturizer With Rice Water &amp; Niacinamide For Glass Skin" class="css-11gn9r6"></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Mamaearth Rice Oil-Free Face Moisturizer With Rice Water &amp; N...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹319</span></span><span class="css-111z9ua">₹281</span><span class="css-cjd9an">12% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->6965<!-- --> <!-- -->)</span></div><div class="css-i9shm8"></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class=" css-1oxhof2"><span class="btn-text">Add to Bag</span></button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1jnild6">FEATURED</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/murad-essential-c-firming-radiance-day-cream/p/8574535?productId=8574535&amp;pps=9"><div class="css-43m2vm"><div class="lazy-load-wrap"><img src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/0/5/05020d9MURAD00000139_1.jpg" alt="Murad Essential-C Firming Radiance Day Cream" class="css-11gn9r6"></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Murad Essential-C Firming Radiance Day Cream</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹9050</span></span><span class="css-111z9ua">₹6788</span><span class="css-cjd9an">25% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->27<!-- --> <!-- -->)</span></div><div class="css-i9shm8"></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class=" css-1oxhof2"><span class="btn-text">Add to Bag</span></button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1l2ejhs">AD</li><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/cetaphil-moisturising-cream/p/392484?productId=392484&amp;pps=10"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Cetaphil Moisturising Cream</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹669</span></span><span class="css-111z9ua">₹562</span><span class="css-cjd9an">16% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->75768<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">3 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/dot-key-ceramides-hyaluronic-barrier-repair-moisturizer/p/15692441?productId=15692441&amp;pps=11"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Dot &amp; Key Hyaluronic + Ceramide Barrier Repair Hydrating Fac...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹395</span></span><span class="css-111z9ua">₹336</span><span class="css-cjd9an">15% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Free Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->52426<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/clinique-moisture-surge-100h-auto-replenishing-hydrator/p/1129289?productId=1129289&amp;pps=12"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Clinique Moisture Surge 100h Auto-replenishing Hydrator (Moi...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹1200</span></span><span class="css-111z9ua">₹950</span><span class="css-cjd9an">21% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->27116<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">5 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/cerave-moisturizing-cream-for-dry-to-very-dry-skin-with-ceramides-hyaluronic-acid/p/13169472?productId=13169472&amp;pps=13"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">CeraVe Moisturizer Cream For Dry Skin With Ceramides &amp; Hyalu...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹430</span></span><span class="css-111z9ua">₹366</span><span class="css-cjd9an">15% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->19819<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1l2ejhs">AD</li><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/ponds-super-light-gel-moisturiser/p/502719?productId=502719&amp;pps=14"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Ponds Super Light Gel Oil Free Moisturiser With Hyaluronic A...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹830</span></span><span class="css-111z9ua">₹415</span><span class="css-cjd9an">50% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->196685<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">4 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/cetaphil-moisturising-lotion-for-dry-to-normal-sensitive-skin/p/12999624?productId=12999624&amp;pps=15"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Cetaphil Moisturising Lotion For Dry To Normal Sensitive Ski...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹620</span></span><span class="css-111z9ua">₹521</span><span class="css-cjd9an">16% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->50989<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">3 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/neutrogena-hydro-boost-water-gel/p/875156?productId=875156&amp;pps=16"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Neutrogena Hydro Boost Hyaluronic Acid Water Gel Light Face ...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹1190</span></span><span class="css-111z9ua">₹750</span><span class="css-cjd9an">37% Off</span></div><p color="0" class="css-1kzcg63">Get Complimentary Product</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->64141<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/embryolisse-lait-creme-concentre/p/403564?productId=403564&amp;pps=17"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><img src="https://images-static.nykaa.com/media/Ontherisefinal.png" class="css-1xehky4"><div class="css-1rd7vky"><div class="css-xrzmfa">Embryolisse Lait-Creme Concentre</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹1525</span></span><span class="css-111z9ua">₹1373</span><span class="css-cjd9an">10% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->11559<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">2 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1l2ejhs">AD</li><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/nivea-soft-cream/p/6004?productId=6004&amp;pps=18"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">NIVEA Soft Vit E Light Non Sticky Face Moisturiser Cream Fre...</div><div class="css-1d0jf8e"><span class="css-111z9ua">₹400</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->53841<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">4 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/plum-thinkderma-2percent-niacinamide-rice-water-clear-moisture-gel-cream/p/10489448?productId=10489448&amp;pps=19"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Plum 2% Niacinamide &amp; Rice Water Moisturiser - Lightweight G...</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹525</span></span><span class="css-111z9ua">₹446</span><span class="css-cjd9an">15% Off</span></div><p color="0" class="css-1kzcg63">Enjoy Complimentary Gift</p><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->17092<!-- --> <!-- -->)</span></div><div class="css-i9shm8"></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class=" css-1oxhof2"><span class="btn-text">Add to Bag</span></button></div></div></div></div><div class="productWrapper css-17nge1h"><div class="css-ifdzs8"><div class="css-d5z3ro"><div class="css-wkluxr"><ul class="css-ycjyr6"><li aria-hidden="true" class="custom-tag css-1bse542">BESTSELLER</li></ul></div><a target="_blank" rel="noopener noreferrer" class="css-qlopj4" href="/lakme-absolute-perfect-radiance-skin-brightening-day-creme/p/588069?productId=588069&amp;pps=20"><div class="css-43m2vm"><div class="lazy-load-wrap"><div class="css-1vdt00l"></div></div></div><div class="css-1rd7vky"><div class="css-xrzmfa">Lakme Absolute Perfect Radiance Skin Brightening Day Creme</div><div class="css-1d0jf8e"><span class="css-17x46n5"><span>₹415</span></span><span class="css-111z9ua">₹270</span><span class="css-cjd9an">35% Off</span></div><div class="css-wskh5y"><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 17.42L6.25 21.54C6.1816 21.5921 6.09823 21.6207 6.01227 21.6217C5.9263 21.6227 5.8423 21.596 5.77272 21.5455C5.70314 21.495 5.65169 21.4234 5.62598 21.3413C5.60027 21.2593 5.60168 21.1712 5.63 21.09L7.77 14.35L2.08 10.15C2.01515 10.0984 1.96747 10.0283 1.94325 9.94905C1.91902 9.86979 1.91938 9.78505 1.94429 9.706C1.9692 9.62695 2.01747 9.5573 2.08276 9.50624C2.14805 9.45518 2.22728 9.42511 2.31 9.41999L9.38 9.36999L11.62 2.65999C11.6463 2.57996 11.6972 2.51028 11.7654 2.46088C11.8337 2.41148 11.9158 2.38489 12 2.38489C12.0842 2.38489 12.1663 2.41148 12.2346 2.46088C12.3028 2.51028 12.3537 2.57996 12.38 2.65999L14.62 9.36999L21.69 9.41999C21.7727 9.42511 21.852 9.45518 21.9172 9.50624C21.9825 9.5573 22.0308 9.62695 22.0557 9.706C22.0806 9.78505 22.081 9.86979 22.0568 9.94905C22.0325 10.0283 21.9848 10.0984 21.92 10.15L16.23 14.35L18.37 21.09C18.3983 21.1712 18.3997 21.2593 18.374 21.3413C18.3483 21.4234 18.2969 21.495 18.2273 21.5455C18.1577 21.596 18.0737 21.6227 17.9877 21.6217C17.9018 21.6207 17.8184 21.5921 17.75 21.54L12 17.42Z" fill="black"></path></svg></span><span class="star-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M12 6.24997L13.19 9.82997L13.53 10.83H14.6H18.38L15.38 13.07L14.52 13.71L14.84 14.71L15.98 18.31L12.91 16.11L12 15.56L11.13 16.18L8.06001 18.38L9.20001 14.78L9.52001 13.78L8.66001 13.14L5.66001 10.9H9.43001H10.51L10.85 9.89997L12 6.24997ZM12 2.36997C11.916 2.36806 11.8337 2.39331 11.7652 2.44195C11.6968 2.4906 11.6458 2.56005 11.62 2.63997L9.38001 9.34998L2.31001 9.40997C2.2269 9.41202 2.1465 9.43991 2.07997 9.48976C2.01345 9.53961 1.96411 9.60895 1.93881 9.68814C1.91352 9.76732 1.91352 9.85243 1.93883 9.93161C1.96413 10.0108 2.01348 10.0801 2.08001 10.13L7.77001 14.33L5.63001 21.07C5.61093 21.1306 5.60657 21.1948 5.61727 21.2575C5.62798 21.3201 5.65344 21.3792 5.69155 21.4301C5.72967 21.4809 5.77934 21.5219 5.83646 21.5497C5.89358 21.5775 5.95649 21.5913 6.02001 21.59C6.10177 21.589 6.18156 21.5647 6.25001 21.52L12 17.41L17.75 21.52C17.8185 21.5647 17.8982 21.589 17.98 21.59C18.0435 21.5913 18.1064 21.5775 18.1636 21.5497C18.2207 21.5219 18.2703 21.4809 18.3085 21.4301C18.3466 21.3792 18.372 21.3201 18.3827 21.2575C18.3934 21.1948 18.3891 21.1306 18.37 21.07L16.23 14.33L21.92 10.13C21.9865 10.0801 22.0359 10.0108 22.0612 9.93161C22.0865 9.85243 22.0865 9.76732 22.0612 9.68814C22.0359 9.60895 21.9866 9.53961 21.92 9.48976C21.8535 9.43991 21.7731 9.41202 21.69 9.40997L14.62 9.34998L12.38 2.63997C12.3542 2.56005 12.3033 2.4906 12.2348 2.44195C12.1663 2.39331 12.084 2.36806 12 2.36997Z" fill="black"></path></svg></span><span class="css-1qbvrhp">(<!-- --> <!-- -->43734<!-- --> <!-- -->)</span></div><div class="css-i9shm8"><div class="css-ijlamg">4 sizes</div></div></div></a></div><div class="showBottomAction hide"><div class="css-1hd8apt"><button type="button" class="wishlist_button_text css-17jex54"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 23 20"><title>Heart icon</title><path class="heart-icon-path" fill="#fff" stroke="currentColor" d="M11.4967297,19.0021565 C12.1501607,18.4744665 15.7313591,16.1461023 16.6556949,15.4660553 C20.4639993,12.6642314 22.5,9.83806845 22.500204,6.31427989 C22.4080534,3.08900922 19.7336922,0.5 16.5,0.5 C14.6798666,0.5 13.0132876,1.30878098 11.8904344,2.71234752 L11.5,3.20039053 L11.1095656,2.71234752 C9.98671236,1.30878098 8.32013337,0.5 6.5,0.5 C3.16873226,0.5 0.5,3.08355995 0.5,6.3 C0.5,9.87466924 2.55294628,12.7216506 6.38828771,15.5301224 C7.34346545,16.229562 10.7334347,18.4195137 11.4967297,19.0021565 Z"></path></svg></button><button type="button" class="css-iyqsry">Preview Size</button></div></div></div></div></div><div class="css-fn0ggt"><span class="css-62qqre">Page 1 of 97</span><a class="css-flzkbk"><svg class="arrow-icon" width="13" height="7" viewBox="0 0 14 8" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.499978 1.24994C0.499217 1.11833 0.524442 0.98787 0.574206 0.866033C0.623971 0.744195 0.697298 0.633379 0.789979 0.539939C0.882942 0.446211 0.993542 0.371816 1.1154 0.321048C1.23726 0.270279 1.36797 0.244141 1.49998 0.244141C1.63199 0.244141 1.7627 0.270279 1.88455 0.321048C2.00641 0.371816 2.11701 0.446211 2.20998 0.539939L6.99998 5.33994L11.79 0.539939C11.9836 0.351635 12.2441 0.247954 12.5141 0.251705C12.7842 0.255456 13.0417 0.366331 13.23 0.559939C13.4183 0.753547 13.522 1.01403 13.5182 1.28408C13.5145 1.55413 13.4036 1.81164 13.21 1.99994L7.70998 7.49994C7.61702 7.59367 7.50641 7.66806 7.38456 7.71883C7.2627 7.7696 7.13199 7.79574 6.99998 7.79574C6.86797 7.79574 6.73726 7.7696 6.6154 7.71883C6.49354 7.66806 6.38294 7.59367 6.28998 7.49994L0.789979 1.99994C0.692368 1.9018 0.616191 1.78447 0.566272 1.65537C0.516353 1.52627 0.493779 1.38821 0.499978 1.24994Z" fill=""></path></svg></a><div class="css-8u7lru"><a class="active css-10bo00h">1</a><a class=" css-10bo00h">2</a><a class=" css-10bo00h">3</a><a class=" css-10bo00h">4</a><a class=" css-10bo00h">5</a></div><a class="css-1zi560"><svg class="arrow-icon" width="13" height="7" viewBox="0 0 14 8" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.499978 1.24994C0.499217 1.11833 0.524442 0.98787 0.574206 0.866033C0.623971 0.744195 0.697298 0.633379 0.789979 0.539939C0.882942 0.446211 0.993542 0.371816 1.1154 0.321048C1.23726 0.270279 1.36797 0.244141 1.49998 0.244141C1.63199 0.244141 1.7627 0.270279 1.88455 0.321048C2.00641 0.371816 2.11701 0.446211 2.20998 0.539939L6.99998 5.33994L11.79 0.539939C11.9836 0.351635 12.2441 0.247954 12.5141 0.251705C12.7842 0.255456 13.0417 0.366331 13.23 0.559939C13.4183 0.753547 13.522 1.01403 13.5182 1.28408C13.5145 1.55413 13.4036 1.81164 13.21 1.99994L7.70998 7.49994C7.61702 7.59367 7.50641 7.66806 7.38456 7.71883C7.2627 7.7696 7.13199 7.79574 6.99998 7.79574C6.86797 7.79574 6.73726 7.7696 6.6154 7.71883C6.49354 7.66806 6.38294 7.59367 6.28998 7.49994L0.789979 1.99994C0.692368 1.9018 0.616191 1.78447 0.566272 1.65537C0.516353 1.52627 0.493779 1.38821 0.499978 1.24994Z" fill=""></path></svg></a></div></div>
                     """)
print(soup.prettify())


<div class="product-listing">
 <div class="css-llpqn7" id="product-list-wrap">
  <div class="productWrapper css-17nge1h">
   <div class="css-ifdzs8">
    <div class="css-d5z3ro">
     <div class="css-wkluxr">
      <ul class="css-ycjyr6">
       <li aria-hidden="true" class="custom-tag css-1jnild6">
        FEATURED
       </li>
      </ul>
     </div>
     <a class="css-qlopj4" href="/dr-althea-resveratrol-345na-intensive-repair-cream/p/844890?productId=844890&amp;pps=1" rel="noopener noreferrer" target="_blank">
      <div class="css-43m2vm">
       <img alt="Dr.Althea 345 Relief Cream: Soothing &amp; Barrier Repair Cream with power of Niacinamide &amp; Panthenol" class="css-11gn9r6" src="https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/6/5/657b0558809447251394_0.jpg"/>
      </div>
      <img class="css-1xehky4" src="https://images-static.nykaa.com/media/OnlyatNykaaFinal.png"/>
      <div class="css-1rd7vky">
       <div class="css-xrzmfa">
        

In [5]:
names  = list(map(lambda x : (x.text).replace("...","") ,soup.select(".css-xrzmfa")))
names

['Dr.Althea 345 Relief Cream: Soothing & Barrier Repair Cream ',
 'Bioderma Niacinamide Moisturizer - Atoderm Creme Ultra-Boost',
 'Lakmé Peach Creme Moisturiser, Ceramide & Peptide, Skin Barr',
 'Forest Essentials Hydrating Facial Moisturiser with SPF 30 P',
 'Dot & Key Vitamin C + E Super Bright Face Moisturizer For Gl',
 'La Roche-Posay Cicaplast Baume B5+ Repair Moisturizer Balm, ',
 'Foxtale Nourishing Ceramide Moisturiser for 100hrs of Hydrat',
 'Mamaearth Rice Oil-Free Face Moisturizer With Rice Water & N',
 'Murad Essential-C Firming Radiance Day Cream',
 'Cetaphil Moisturising Cream',
 'Dot & Key Hyaluronic + Ceramide Barrier Repair Hydrating Fac',
 'Clinique Moisture Surge 100h Auto-replenishing Hydrator (Moi',
 'CeraVe Moisturizer Cream For Dry Skin With Ceramides & Hyalu',
 'Ponds Super Light Gel Oil Free Moisturiser With Hyaluronic A',
 'Cetaphil Moisturising Lotion For Dry To Normal Sensitive Ski',
 'Neutrogena Hydro Boost Hyaluronic Acid Water Gel Light Face ',
 'Embryol

In [6]:
prices = list(map(lambda x : int(x.next_sibling.next_element.text.replace("₹","")) ,soup.select(".css-xrzmfa")))

In [7]:
prices

[2499,
 699,
 780,
 1695,
 495,
 550,
 395,
 319,
 9050,
 669,
 395,
 1200,
 430,
 830,
 620,
 1190,
 1525,
 400,
 525,
 415]

In [8]:
import csv
with open("data1.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(["name","price"])
    for i in range(len(names)):          
        writer.writerow((names[i],prices[i]))

In [9]:
import csv
with open("data.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(["name","price"])
    for i in zip(names,prices):
        writer.writerow(i)

In [10]:
data = dict(names= names , prices = prices)

In [13]:
import pandas as pd
df = pd.DataFrame(data)
df.to_excel("my_csv.xlsx")

In [12]:
pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>names</th>\n      <th>prices</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Dr.Althea 345 Relief Cream: Soothing &amp; Barrier Repair Cream</td>\n      <td>2499</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Bioderma Niacinamide Moisturizer - Atoderm Creme Ultra-Boost</td>\n      <td>699</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Lakmé Peach Creme Moisturiser, Ceramide &amp; Peptide, Skin Barr</td>\n      <td>780</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Forest Essentials Hydrating Facial Moisturiser with SPF 30 P</td>\n      <td>1695</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Dot &amp; Key Vitamin C + E Super Bright Face Moisturizer For Gl</td>\n      <td>495</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>La Roche-Posay Cicaplast Baume B5+ Repair Moisturizer Balm,</td>\n      <td>550</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Foxtale Nourishing Ceramide Moisturiser for 100hrs of Hydrat</td>\n      <td>395</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Mamaearth Rice Oil-Free Face Moisturizer With Rice Water &amp; N</td>\n      <td>319</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Murad Essential-C Firming Radiance Day Cream</td>\n      <td>9050</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Cetaphil Moisturising Cream</td>\n      <td>669</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Dot &amp; Key Hyaluronic + Ceramide Barrier Repair Hydrating Fac</td>\n      <td>395</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Clinique Moisture Surge 100h Auto-replenishing Hydrator (Moi</td>\n      <td>1200</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>CeraVe Moisturizer Cream For Dry Skin With Ceramides &amp; Hyalu</td>\n      <td>430</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Ponds Super Light Gel Oil Free Moisturiser With Hyaluronic A</td>\n      <td>830</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Cetaphil Moisturising Lotion For Dry To Normal Sensitive Ski</td>\n      <td>620</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Neutrogena Hydro Boost Hyaluronic Acid Water Gel Light Face</td>\n      <td>1190</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Embryolisse Lait-Creme Concentre</td>\n      <td>1525</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>NIVEA Soft Vit E Light Non Sticky Face Moisturiser Cream Fre</td>\n      <td>400</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Plum 2% Niacinamide &amp; Rice Water Moisturiser - Lightweight G</td>\n      <td>525</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Lakme Absolute Perfect Radiance Skin Brightening Day Creme</td>\n      <td>415</td>\n    </tr>\n  </tbody>\n</table>